### ISSUE TITLE
release: jenkins job for bumping VERSION fails

### ISSUE THREAD

**Issue by chavafg** [kata-containers/packaging#1026]
# Description of problem

Jenkins job that creates the PRs for bumping `VERSION`'s in repos is failing:
Job:
http://jenkins.katacontainers.io/job/release/build

Jenkinsfile that is used in the job:
https://github.com/kata-containers/packaging/blob/master/Jenkinsfiles/release_pieline/Jenkinsfile

Failure:
```
/tmp/jenkins/workspace/release/packaging/Jenkinsfiles/release_pipeline@tmp/durable-5e9a0d96/script.sh: 2: /tmp/jenkins/workspace/release/packaging/Jenkinsfiles/release_pipeline@tmp/durable-5e9a0d96/script.sh: ./git_credential_cache.sh: not found
```

Taking a look at the history of the Jenkinsfile, I see a change that might have affected the behavior of the job:
https://github.com/kata-containers/packaging/commit/3418d401589d44c1dc6f0de4bad3fd6a40ed29a7

**Comment by mramanathan** [comment]
@chavafg 

As of to-day, that build job link navigates to a `successful` build dated May 6,2020 and the job url points to, http://jenkins.katacontainers.io/job/release/121/

It seems the build retention config is set to retain just one job and the older builds have been purged.

And, the blob URL to Jenkinsfile has been renamed since this issue was created.

Just wondering if this issue is valid, still?

**Comment by chavafg** [comment]
hi @mramanathan 
> Just wondering if this issue is valid, still?

Thanks for remind me closing this. No longer valid, @jcvenegas fixed it.
