### ISSUE TITLE
Stop building community packages for 2.0 and onwards in favour of kata-deploy

### ISSUE THREAD

**Issue by fidencio** [kata-containers/packaging#1120]
Although this may look controversial, kata-deploy is a way simpler, more elegant, and less time consuming way to have kata-containers installed in a way users can taste the project.

This was discussed as part of Today's Kata Architects Meeting (Aug 25th 2020), and the reasoning behind that is to have **one** simple approach that is not time consuming. Fortunately we already have some distros packaging kata (thanks openSUSE, thanks SLE, thanks Fedora, thanks CentOS), but a single project doing the packaging for all possible distributions is something that simply doesn't scale.

As we already have kata-deploy, we must take advantage of that, update our documentation (as mentioned in https://github.com/kata-containers/documentation/issues/708), and move forward with this approach.

**Comment by jodh-intel** [comment]
My concern about this approach is that `kata-deploy` installs static binaries. Since that is done without using a package manager, there is no easy way to notify users that a new release is available.

This problem will mostly affect users of those distros which don't yet package Kata (Debian, etc), but will realistically affect many more users who wish to use the latest release of Kata (the packaged version will lag behind the latest static builds I suspect meaning many users will prefer the `kata-deploy`-installed version of Kata over the packaged version).

What we *could* consider doing is adding a check to `kata-runtime kata-check` that compares the currently installed (static) version with the newest static release (by querying https://github.com/kata-containers/kata-containers/releases). That check should probably be part of the default checks run by that command, however we must provide a CLI flag to disable that check (something like `--no-network-checks`).

Related:

- https://github.com/kata-containers/documentation/issues/708
- https://github.com/kata-containers/packaging/issues/1119
