### ISSUE TITLE
Provide arm64 OBS images

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/packaging#195]
For parity with x86_64 and #118, we should provide arm64 distro packages too.

**Comment by bilang** [comment]
：）

**Comment by nitkon** [comment]
: )

**Comment by Pennyzct** [comment]
Hi~ @jodh-intel, do you plan to or already be working on this issue? Just got back from a loooooong leave, so sorry for other non-responded arm issues. 😥😟

**Comment by Pennyzct** [comment]
Hi @jodh-intel happy to volunteer and update the process asap ;) @Weichen81 @hejianet

**Comment by jodh-intel** [comment]
Hi @Pennyzct - thanks very much - it's all yours! :smile:

You may have seen this thread on the ML:

- http://lists.katacontainers.io/pipermail/kata-dev/2018-October/000505.html

I'm sure @marcov, @nitkon and @jcvenegas  can help out with any question you have about OBS architecture-specific issues.

**Comment by marcov** [comment]
Hi @Pennyzct, we recently opened a [new issue](#211) to track the process of building for different architectures.

I just sent a new answer to the ML with the next activities planned: http://lists.katacontainers.io/pipermail/kata-dev/2018-October/000507.html
Are you interested in working on any on those?
(btw, I just realized my email client sucks with HTML emails).


To start experimenting, you could set up a new home project on [OBS](https://build.opensuse.org/), or have @jcvenegas create a new one under home:katacontainers. This is e.g. what is doing @nitkon for ppc64le and it's a short term solutions to have packages building for different archs.

**Comment by Weichen81** [comment]
; ) +1 @Pennyzct @jodh-intel

**Comment by jodh-intel** [comment]
I wonder if it's worth putting some notes on the process for adding support for a new architecture to the OBS Kata project. It doesn't need to be a formal doc and could live in a wiki maybe? :)

**Comment by marcov** [comment]
> Hi~@marcov I'm pretty a newbie to OBS. i was trying to set up a new home project home:penny:branches:home:katacontainers:release/runtime following the katacointainers project, am i in a right path?

Hi @Pennyzct, that project path is fine, although if you like, when branching you can give it a shorter/simpler name.
(does not need to contain `branches:home:katacontainers:release`).

Note that `home:katacontainers:releases:x86_64:master` is updated more often than `release`, so you may want to branch from that.

> then i'm trying to edit arch info through `osc meta prj` and `osc build` to see if it works properly.

`osc meta prj`: sounds good (with the -e option), just fyi you could also use the web ui for setting repositories/architectures.

`osc build`: without any other options, this will build for aarch64 only if your host is a aarch64 too.

----

Would you be interested in working on Ubuntu build rules? 

If so:
1. you'll need to add this repository `Ubuntu:18.04:Ports`. These are the packages available: https://build.opensuse.org/project/meta/Ubuntu:18.04:Ports . As you see there are multiple repositories there (standard, universe,update).
2. you'll need to change build rules for deb (`debian.*` files) so that the golang package in the Ubuntu repository is used instead of the binary copy in the packages sources.

**Comment by Weichen81** [comment]
@jodh-intel About the OBS, we may need to pass some legal issue, and @Pennyzct will attend OSSEU next week to delivery a talk, so she may need sometime to start the OBS work. She is rehearsing the presentation hard  ; )

**Comment by jodh-intel** [comment]
Hi @Weichen81 - thanks for the update. Sounds like we need a volunteer with ARM skills :)

**Comment by Pennyzct** [comment]
Hi guys
We're working on the OBS issue now and I'm trying to follow the instruction [here](https://github.com/kata-containers/packaging/tree/master/obs-packaging). Hope I'm in the right direction.
Here is the thing, I got errors as follows:
```
$ CI="true" LOCAL="1" OBS_SUBPROJECT="aarch64:alpha" ./build_all.sh  master
======= Updating qemu-vanilla =======
home:katacontainers:aarch64:alpha/qemu-vanilla
Server returned an error: HTTP Error 404: Not Found
Error getting meta for project 'home%3Akatacontainers%3Aaarch64%3Aalpha' package 'qemu-vanilla'
home:katacontainers:aarch64:alpha
ERROR: failed to checkout:makeurl: https://api.opensuse.org ['source', 'home%3Akatacontainers%3Aaarch64%3Aalpha', 'qemu-vanilla', '_meta'] {}
```
Do I need to acquire some authentications/privileges here? 😵😵😵 or I just went the wrong path😂

cc @stevecapperarm
