### ISSUE TITLE
Architecture independent packaging for OBS

### ISSUE THREAD

**Issue by marcov** [kata-containers/packaging#211]
(I know there are already open issues for [PPC](#118) and [ARM](#195), but I wanted to open a new one not to limit to a specific architecture).

This issue is to track the tasks needed to have packages building on OBS for more than just x86_64. 

Given that there are multiple packages and architectures to support , I foresee this is going to take some time.

I can contribute to this, and having colleagues at SUSE working on packaging will make things easier :)

**Comment by marcov** [comment]
cc @jcvenegas 

@nitkon I see you started working for ppc64le support and already provided some updates to the packages. 
Are you still able to progress and do you plan continue working on it? If so, maybe we can find a way to split some of the tasks to advance faster.

**Comment by jcvenegas** [comment]
@marcov  sounds good based on the work from @nitkon , I seen a couple of things to improve,

### qemu spec
For qemu we need to make the spec file  arch independent
https://github.com/kata-containers/packaging/blob/master/obs-packaging/qemu-vanilla/qemu-vanilla.spec-template#L116

### kernel config variable
For the kernel we need to set the right arch name,  
```
[  102s] + make -s ARCH=ppc64le oldconfig
[  103s] Makefile:505: arch/ppc64le/Makefile: No such file or directory
```
###  unresolvable dependencies

There are some distros with unresolvable dependencies I am not sure if we need to add more repositories 
- Fedora 26
- Redhad 7
- openSUSE_Leap_42.3 @marcov may know a bit more here (https://build.opensuse.org/project/monitor/home:katacontainers:alpha:ppc64le:1.3.0?arch_ppc64le=1&defaults=0&repo_openSUSE_Leap_42_3=1&unresolvable=1)
- All the ubuntu distros.

**Comment by jcvenegas** [comment]
I am taking care of update golang hash depending on the version.

**Comment by nitkon** [comment]
@jcvenegas : I am testing my patch for golang hash dependency. Live results here: https://build.opensuse.org/project/show/home:katacontainers:alpha:ppc64le:1.3.0

Will send my patch asap.

**Comment by nitkon** [comment]
@jcvenegas : Is that fine?

**Comment by nitkon** [comment]
@marcov: Yes, I plan to continue to work on this. As @jcvenegas rightly pointed out, the failures we see here (https://build.opensuse.org/project/show/home:katacontainers:alpha:ppc64le:1.3.0) today are due to the reasons mentioned by him. Qemu, kernel and OBS _service file needs to be fixed(https://github.com/kata-containers/packaging/pull/213) . Also as mentioned in the above comment, we need to back all the dictros supported by Kata by ppc64le/arm instances on OBS so that we do not get "unresolvable" message in our build results.
Lets split and try to advance faster on this. cc: @jcvenegas 
Also, another thing that we discussed earlier is https://github.com/kata-containers/packaging/pull/192#discussion_r219845530 . I still see failure to when I try to push a release `PUSH=1 OBS_SUBPROJECT="alpha:ppc64le:1.3.0" bash -x ./build_from_docker.sh 1.3.0` with an error:

```
update runtime
+ ./update.sh -p 1.3.0
/usr/local/go/bin/go
INFO: requires:
INFO: proxy 1.3.0+git.6ddb006-5
INFO: shim 1.3.0+git.5fbf1f0-5
INFO: kata-linux-container 4.14.67.12-5
INFO: ksm-throttler 1.3.0+git.6e903fb-5
INFO: image 1.3.0-5
Server returned an error: HTTP Error 404: Not Found
Error getting meta for project 'home%3Akatacontainers%3Aalpha%3Appc64le%3A1.3.0' package 'qemu-lite'
home:katacontainers:alpha:ppc64le:1.3.0/qemu-lite
ERROR: failed to checkout:makeurl: https://api.opensuse.org ['source', 'home%3Akatacontainers%3Aalpha%3Appc64le%3A1.3.0', 'qemu-lite', '_meta'] {}
```

**Comment by nitkon** [comment]
@marcov : That's what even I also use to think.  Yes, that's what the message in OBS says- "package missing". But AFAIU it also means the ppc64le instance is unavailable for that distro despite marking it under 'repositories' section. 
![unresolvable](https://user-images.githubusercontent.com/35655196/46460800-b6e41900-c7da-11e8-9608-23f25da22253.png)
