### ISSUE TITLE
hypervisor config

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/packaging#27]
Hypervisor config script uses some options only in newer bash versions. 

This fails silently in centos leading to build a qemu without all options we want.

**Comment by jodh-intel** [comment]
This appears to be because centos provides bash 4.2.46 and although that version supports arrays, it doesn't support passing a reference to a variable into a function with `local -n`.

I've got part of a fix, but I'm actually wondering if we should consider rewriting the script in python or go to avoid problems like this.
