### ISSUE TITLE
releases: stable/maintained: maintain a visible list of current maintained releases

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/packaging#336]
We state over in the [Stable Branch Strategy doc](https://github.com/kata-containers/documentation/blob/master/Stable-Branch-Strategy.md#branch-management) that:

> Kata Containers will maintain two stable release branches

but, as github is [not great at listing releases](https://github.com/kata-containers/runtime/releases), we should make a much more obvious place where we list which versions are currently being maintained (and what their current 'tip' versions are).

We should of course aim to automate and/or make error free this process as much as possible, so we should try to integrate the updates into our [Release document](https://github.com/kata-containers/documentation/blob/master/Releases.md) and [Release checklist](https://github.com/kata-containers/documentation/blob/master/Release-Checklist.md).

I have in mind a table something like:

| Type | Version | Last updated | Originally released |
| ---- | ---- | ---- | ---- |
| stable | [1.5.0](https://github.com/kata-containers/runtime/releases/tag/1.5.0) | 2019-01-22 | 2019-01-22 |
| stable | [1.4.2](https://github.com/kata-containers/runtime/releases/tag/1.4.2) | 2019-01-10 | 2018-11-23 |

If we wanted we could list out all previous version, and add a 'Deprecated' column. It could get quite big if we start doing frequent releases though.

I'm also not sure if we want to invest the effort to automate this if we are going to move to [using package cloud](https://github.com/kata-containers/packaging/issues/328) - we may be able to survive with manual updates in the interim.

I think we **do** need to advertise our stable versions on the docs, community and runtime repos though.

/cc @jcvenegas @egernst @gnawux @jodh-intel

**Comment by jodh-intel** [comment]
Yep - this is basically a dup of the unresolved https://github.com/kata-containers/documentation/issues/234 (see https://github.com/kata-containers/documentation/issues/234#issuecomment-417664632).

At the risk of sounding like a broken record, I think forking the doc repo would make life easier for us too: https://github.com/kata-containers/documentation/issues/246.

I think this needs to be brought up at the Architecture Committee meeting and ultimately our chosen strategy needs to be ratified by the Architecture Committee and documented in our process docs.

The simplest way to automate this I think is to update the [release tooling](https://github.com/kata-containers/packaging/tree/master/release) to:

- Handle any doc repo forking and updating of the versions encoded into a particular branches install docs.

- Generate a landing page document listing all available releases for users (with pointers off the the various versions of the install docs).

  That landing page should list the lifespan of the branch (even if that is documented as "until version X.Y.Z is released").

- Identify any old/stale stable branches so that we can arrange to notify users that they should upgrade using all available channels (release notes, mailing list, twitter, blah).

**Comment by jodh-intel** [comment]
Adding @ttx as he may also have thoughts on this.

**Comment by jodh-intel** [comment]
Oh, and @marcov as it will potentially touch on OBS/Packagecloud...

**Comment by ttx** [comment]
I agree that the two choices are:
1- a lightweight page listing releases
2- a fully automated release process that updates a website

For OpenStack we are using (2) (see http://git.openstack.org/cgit/openstack/releases/tree/, which gets processed through Zuul jobs that trigger tags, build, sign and upload source tarballs and finally publish release information to https://releases.openstack.org). I'm happy to walk you through that setup but I would advise to use (1) while you determine how to best do (2) :)

**Comment by jodh-intel** [comment]
@ganeshmaharaj - Given your excellent backporting work recently, do you want to tal at the possibilities here?
