### ISSUE TITLE
kata-deploy: Multiple entries for "crio.runtime.runtimes.kata-qemu" added to cri-o conf file

### ISSUE THREAD

**Issue by amshinde** [kata-containers/packaging#374]
Not sure what sequence of steps caused it, but ended up with multiple "crio.runtime.runtimes.kata-qemu"
and "crio.runtime.runtimes.kata-fc" in the cri-o conf file, causing cri-o to fail to start.
kata-deploy should check for the runtime entries, if they are already present before adding them.

**Comment by amshinde** [comment]
cc @egernst

**Comment by jodh-intel** [comment]
It sounds like the following need to be made idempotent:

- https://github.com/kata-containers/tests/blob/master/.ci/configure_crio_for_kata.sh
- https://github.com/kata-containers/tests/blob/master/.ci/configure_containerd_for_kata.sh

**Comment by egernst** [comment]
@amshinde - is this when using the clear linux vagrant example?  

I agree there should be some checking in the kata-deploy scripting for this, to at least:
1) throw a warning
2) modify the line rather than just appending a new one

I could use help with this and would love another contributor to that file.  git blame really likes me :)

**Comment by amshinde** [comment]
@egernst Yes, this is while using the clear linux vagrant example. I have opened a correspoding issue in the clearlinux stack repo.
