### ISSUE TITLE
static binary builds should be hermetic

### ISSUE THREAD

**Issue by egernst** [kata-containers/packaging#393]

**Comment by jodh-intel** [comment]
The following might help to explain this issue, but it might be worth fleshing it out a bit further @egernst :)

- https://landing.google.com/sre/sre-book/chapters/release-engineering/#hermetic-builds-nqslhnid

Essentially, I think we're saying that it's not enough to produce [reproducible binaries](https://en.wikipedia.org/wiki/Reproducible_builds) - we need to guarantee that *the environment used to produce those binaries* is fully recreatable / reproducible at any point in the future such that "the build system can be fully self-contained ("hermetic").

We can't realistically store every version of every compiler/library/package/toolset used to produce a binary in the [versions database](https://github.com/kata-containers/runtime/blob/master/versions.yaml), but we can record those details along with each build. How about we grab the following at the end of each build and store it alongside the binaries as a compressed yaml file?

- [versions database](https://github.com/kata-containers/runtime/blob/master/versions.yaml)
- package list

  `rpm -qa` or `dpkg -l`

The only other issue may be getting access to those particular versions at arbitrary points in the future given:

- package versions may have been superceded (CVE updates, etc).

  old/insecure binaries packages may have been removed or could pose a security risk if we use the exact same version used at the time if package versions were subsequently found to be insecure somehow.

- distro versions may have gone EOL.

  Again, there may be a security / availability issue.

Since our systems are open, I think the availability risk is low as old distro releases are always available afaik, but raising nonetheless just in case someone is aware of an issue in this area?

Related: #165.

**Comment by grahamwhaley** [comment]
Just going to throw in the idea of 'build it in a container', where you may have more control over what versions of packages and what baseline distro version is installed. But, I think that is still going to suffer from the 'things rot and expire' - but maybe we only need things reproducible for the window of their lifetime, and that is short enough that in practice it will not be a real issue.

**Comment by jodh-intel** [comment]
Good idea @grahamwhaley. I seem to recall issues around building in containers but maybe those have now been overcome. It would certainly be simpler to store the name and revision of the docker image, say, for an official image we use to build in that storing all package versions. But I still worry that that may not be enough as we cannot control those docker images (what if all the layers get flattened? I think that would mean we could never get back to the revision we built in). Storing all metadata I guess is the answer ;)

+1 for constraining the need to rebuild within the lifespan of stable releases though which I think you're implying? That would simplify the problem I think.

**Comment by egernst** [comment]
I am glad your SRE reference didn't point here, James: https://en.wikipedia.org/wiki/Hermeticism

My thought was that we should be building in a container.  Last stable release Carlos and I split.  As a result, we had binary size deltas because we used 1.10 and 1.11 Go versions.  It'd be best to containerize to avoid this, and at least get closer to a hermetic build.
