### ISSUE TITLE
[BUG] k8s installation is successful even when the system doesn't have QEMU/KVM installed.

### ISSUE THREAD

**Issue by gaby** [kata-containers/packaging#466]
**Host information:**
- Custom Cluster running in Rancher 2.2.2
- VM with virtualization disabled
- Ubuntu 18.04 LTS
- Latest Docker-CE
- Installed kata-deploy using kubectl.

After following the instructions in: https://github.com/kata-containers/packaging/tree/master/kata-deploy#kubernetes-quick-start

I was surprised to noticed that kata-deploy started and was running, even though my worker node has no virtualization, qemu, or kvm installed. Running uname -a in both the container and my host results in the same value. 

Deployment used: https://raw.githubusercontent.com/kata-containers/packaging/master/kata-deploy/examples/test-deploy-kata-qemu.yaml

Is this deployment file correct? It seems to be missing a lot of labels, are those needed or not?

**More test:** 
I'm pretty sure this is not the intended behavior. So, I decided to run: 

`docker run -v /opt/kata:/opt/kata -v /var/run/dbus:/var/run/dbus -v /run/systemd:/run/systemd -v /etc/docker:/etc/docker -it katadocker/kata-deploy kata-deploy-docker install`

This runs and exits cleanly with 0 errors, even though my VM has no virtualization/qemu/kvm available. The quick start guide doesn't mention that QEMU/KVM needs to be installed in the host.

Running the following commands fail with two different errors:

**Test 1:**
-  `docker run --runtime=kata-qemu -itd alpine` 
-  Fails because QEMU cannot find KVM (expected).

**Test 2:**
- `docker run --runtime=kata-fc -itd alpine`
- Fails because kata-proxy is not found.

**Comment by gabrielcalderon** [comment]
I think the reason the install command doesnt fail within docker is because there no checks at all.

Kata provides "kata-check" but it's not used here. The install/remove script assumes you have a system capable of running QEMU/KVM without even checking.

It's easy to replicate this by running the command inside a VM that has no virtualization capabilities.

The k8s install yaml should use a initContainer with kata-check before trying to install/mess a system host configuration.

**Comment by krsna1729** [comment]
This came up here too https://github.com/clearlinux/cloud-native-setup/issues/89
/cc @egernst @grahamwhaley @mcastelino

**Comment by egernst** [comment]
@gabrielcalderon thanks for opening the issue.  

Indeed, today we don't check - we just happily put the binaries on your host!  You're right, it's an easy enough check, and would be a better user experience to fail early and report the error to the user.

I'm not sure if I'll have cycles in the very short term to add this.  If you have a chance and interest, help would be *much* appreciated, otherwise I'll add this to the backlog for fixing!

**Comment by krsna1729** [comment]
`runtimeClassName` today lacks awareness of the nodes that implement a `runtimeClass`. This is a limitation with a fix targeted in k8s 1.15. 

So until then - 
1. the script could use kata-check and sleep early just like in case of docker runtime (vs cri-o/containerd)
2. workload examples carry `nodeSelector` for `katacontainers.io/kata-runtime=true`

**Comment by gabrielcalderon** [comment]
I wouldn't mind coming with a fix for this, but currently I can't get my VM's to detect KVM. Is there a way to run kata using "-cpu qemu" instead of x86 simulation?

I'm running VirtualBox with Ubuntu 18.04 and AMD Ryzen 1700x.

Before Kata, I was using HyperContainers and they could be run without kvm.
