### ISSUE TITLE
Build and artifact storage for kata containers

### ISSUE THREAD

**Issue by egernst** [kata-containers/packaging#5]
In Clear Containers, OBS was used for handling the packaging needs.  This had a number of draw backs.  Need to come up with solution and plan for meeting our packaging needs in Kata.

**Comment by egernst** [comment]
@sameo @gnawux

**Comment by gnawux** [comment]
set up a CI task for packaging? for hyper, we regularly run a docker image for making binary packages and upload them.

**Comment by ajaeger** [comment]
What were the OBS drawbacks? I'd like to check whether some of these can be overcome?

**Comment by cboylan** [comment]
Before we dig in too much I agree it would be good to understand how other systems have failed or been sub optimal. Also, a general description of the  problem you are trying to solve may help us understand those issues better.

As for OpenStack resource specifics, the OpenStack Developer Infrastructure runs a CI system that can execute arbitrary code in jobs running on sandboxed VMs. In the past we have used this to build Debian packages. Specifically jobs would build packages using whatever the preferred Debian packagers' tooling was and then upload them to https://tarballs.openstack.org which is our current artifact hosting system. You can perform testing on the packages before and after they are published.

We've also recently updated the CI system to allow projects to define project specific secrets which can be used by jobs to perform actions like publishing packages to arbitrary locations with little effort. That is currently being used by some projects to publish to dockerhub so you are not limited to https://tarballs.openstack.org.

Finally this all works against our Gerrit hosted projects today. We have Github mostly working but are still dogfooding it with Zuul and Ansible before we open it up to a larger audience, but I expect this will be an option soon.

**Comment by jodh-intel** [comment]
I believe we have been affected multiple times by OBS maintenance windows. Wasn't that the main issue @jcvenegas, @erick0z ?

**Comment by jcvenegas** [comment]
@jodh-intel yes, if Clear Containers we use the public OBS service sometimes been affected multiple times by OBS maintenance window (and sometimes takes several time). For the Clear Containers CI we also use precompiled binaries for the kernel and guest OS to redice CI times and using OBS repositories used to break the CI build because by time to time the servers was down.

**Comment by erick0z** [comment]
For Clear Containers, a few OBS Infrastructure failures and maintenance windows affected the release cadence (once a week) and the ability to retrieve packages as well. These are not recurrent issues but when they happen, we end being unable to either create new packages or provide packages to our users/potential users. I would personally like a solution that we have full control of it and we can easily integrate with a CI. I like the containerized approach so, we can provide a container image or a Dockerfile in order to let users to create their own packages relatively easy. I would like to see other proposals as well.

**Comment by jodh-intel** [comment]
One obvious solution might be to host our own [OBS](https://github.com/openSUSE/obs-build) service (packaged as `obs-build` for Debian/Ubuntu/Fedora) so we have more control.

**Comment by ydjainopensource** [comment]
@jodh-intel Exactly what I was wondering all this long.....I think Jess had offered Azure services if needed during the last meeting if at all hosting the service is an issue

**Comment by egernst** [comment]
@jodh-intel - this seems pretty pragmatic to me.  OBS has worked well from a technology standpoint, I think we've just been disappointed by system availability when using their (free) infrastructure/compute.  Assuming we go with this, I  think we have two options, to which I'd need better understanding of the pros/cons:

1. Making use of the azure nodes/hosting we have available (thanks @jessfraz) or,
2. Seeing what is available from the openstack infra (@cboylan, I'd look to you for input here).

If we can gather more information, this may be a good topic for the next architecture forum...

**Comment by cboylan** [comment]
A high level description of what the openstack infra team can provide is a CI system that allows you to run mostly arbitrary code in single use VMs. For package building this means that you can set up jobs to build packages however you like (sbuild, delorean, whatever) then copy them off the build node to some hosting service. https://tarballs.openstack.org is our easy mode artifact storage location, jobs copy data there and we host it via http. However, via the use of job secrets you can theoretically publish anywhere you have credentials and the right tools to publish to.

This has been used in the past to build the Debian packages for OpenStack (but moved back to alioth or salsa or whatever the Debian hosting system is now as the Debian developers felt more at home there). Similarly to this there are projects like loci and kolla using these single use build nodes to produce docker images and upload them to dockerhub.

As for running OBS it has come up in past specs around building packages for OpenStack, https://review.openstack.org/#/c/179713/2/specs/build_distribution_packages.rst. Specific concerns we've had with it appear to be the fact that we already have an isolated build system and OBS doesn't allow package builders to use the preferred tooling of $distro (though having not used OBS I'm not entirely sure how true that is). It is probably worth looking into how true that is as you may want to use distro preferred tooling simply so that it is easier for distros to pick up packaging for Kata on their end.

**Comment by cboylan** [comment]
To get an idea of what the configuration for running jobs that publish artifacts (in this case docker images) look like we can look at loci's configs.

https://github.com/openstack/loci/blob/master/.zuul.d/nova.yaml#L21-L26 defines a publish job that specifies a playbook to do the actual publishing step. It relies on its parent job to do the image build. The playbook to do the build can be found at https://github.com/openstack/loci/blob/master/playbooks/loci-builder.yaml and the playbook that does the publish is at https://github.com/openstack/loci/blob/master/playbooks/push.yaml.

**Comment by jodh-intel** [comment]
Related: #1.

**Comment by jodh-intel** [comment]
Removed `release-gating` label as issue opened 2 years ago ;)
