### ISSUE TITLE
kata-runtime dependencies are not strict for Debian packages

### ISSUE THREAD

**Issue by marcov** [kata-containers/packaging#508]
Also Debian control files should specify `=` instead of `>=` for dependecies version.

**Comment by marcov** [comment]
I feel like the  fix should be backported to the stable branches. 
Are there any directions of what to include in a backport commit? @jodh-intel

**Comment by jodh-intel** [comment]
Not really, aside from using the same issue for the stable PRs (even like this one if the issue is closed). We should evolve some guidance on this and put it into https://github.com/kata-containers/documentation/blob/master/Stable-Branch-Strategy.md, or https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#stable-branch-backports.

**Comment by grahamwhaley** [comment]
Apart from the backport guide that is eh @jodh-intel ;-)
https://github.com/kata-containers/community/blob/master/Backport-Guide.md

**Comment by jodh-intel** [comment]
Thanks for reminding me author - I'd forgotten about that one (although thankfully there is a link to in the contributing guide).

btw, I'm planning to enhance the markdown checker to make our docs less likely to get lost. Watch this space...
