### ISSUE TITLE
kata-fc runtime installed with kata-deploy for docker errors out

### ISSUE THREAD

**Issue by amshinde** [kata-containers/packaging#543]
```
$ sudo docker run -it --runtime=kata-fc debian sh
docker: Error response from daemon: OCI runtime create failed: file /usr/libexec/kata-containers/kata-proxy does not exist: unknown.
```

**Comment by amshinde** [comment]
This seems to be an issue with the runtime which checks for the proxy path in case of firecracker.
firecracker uses vhost-vsock, so we should omit this check.

cc @egernst

**Comment by egernst** [comment]
The check is carried out since the [proxy.kata] exists in the resulting toml.  This is an issue for FC and NEMU tomls, and is generic; not something in kata-deploy (ie, an issue with what is in the release artifacts).  Let's open an issue in runtime repo to track.  We can either make the "check logic" smarter, or update the toml to drop this section, or do both...

**Comment by egernst** [comment]
Fixed now

**Comment by egernst** [comment]
see https://github.com/kata-containers/runtime/issues/1761
