### ISSUE TITLE
Should we provide multiple guest kernel config files?

### ISSUE THREAD

**Issue by Weichen81** [kata-containers/packaging#55]
Hi,

Currently, we provide only one guest kernel config file for users to install guest kernel images. Should we provide more kernel config files for users to select? For example, we can provide config files for recent releases. e.g., from 4.14 ~ 4.16
{arch}_kata_kvm_4.14.x
{arch}_kata_kvm_4.15.x
{arch}_kata_kvm_4.16.x
and 
{arch}_kata_kvm_generic for latest upstream code?

@Pennyzct @jodh-intel @grahamwhaley

**Comment by jodh-intel** [comment]
This sounds like a good idea. I'd just be concerned about the maintenance impact of supporting multiple kernels per architecture. Our documented process (which could be changed of course) is that we only support the newest longterm kernel release:

- https://github.com/kata-containers/documentation/blob/master/Upgrading.md#guest-kernel

So in terms of the kernel config, I was imagining that when 4.15 is released, we would switch the guest kernel to that version and probably delete the 4.14 configs, signalling that the 4.14 config was no longer being maintained.

Another way to provide more flexibility might be for us to define a "minimum set" of Kata Containers kernel config options per architecture so that a user could apply those to their upstream kernel config. Ideally, we'd have a script that could generate a minimal working kernel config per architecture based on that minimum set (see https://github.com/kata-containers/packaging/issues/8), but I'm not sure how easy that would be to get working given the somewhat arcane nature of the kernel config system (where the config file does *not* contain all config options).

/cc @egernst.

**Comment by jodh-intel** [comment]
See also: #56.

**Comment by Weichen81** [comment]
@jodh-intel For the first way, I think we can keep both 4.14 and 4.15 configs. And update the guest install scripts to fetch the 4.15 configs. The benefit is that, once the 4.15 kernel failed on some architectures, the user can fall back to use 4.14 kernel easily.

The second way sounds better.  But how to generate a workable minimal kernel config puzzle me too.

**Comment by gkennedy12** [comment]
Just to be clear, currently there is no way to boot a different kernel per VM, right? There would have to be support for multiple configuration.toml files to accomplish this, correct?

**Comment by jodh-intel** [comment]
Hi @gkennedy12 - you are essentially correct - the runtime will boot the VM using whichever kernel is specified in `configuration.toml` *at the time* the container is created.

That does imply long-running containers may be running with an older kernel that new ones though. For this reason, we added a special `--kata-all` option to the `list` command which shows the kernel the VM is using *and* the latest kernel version available:

```
$ sudo kata-runtime list --kata-all
```

That atleast allows you to establish if any containers are "stale" (in fact there is a "STALE" field to make it even clearer :)

But, there's more... the [virtcontainers package](https://github.com/kata-containers/runtime/tree/master/virtcontainers) used by the runtime provides a way to specify alternative assets (image, kernel, hypervisor, firmware) inside the OCI `config.json` [annotations](https://github.com/opencontainers/runtime-spec/blob/master/config.md#annotations). See:

- https://github.com/kata-containers/runtime/blob/master/virtcontainers/asset.go
- https://github.com/kata-containers/runtime/blob/master/virtcontainers/pkg/annotations/annotations.go

**Comment by jodh-intel** [comment]
@Weichen81 - I put some more comments on #8 but I'd really value some input on whether the approach on that issue is feasible.

**Comment by jodh-intel** [comment]
Related #56.

**Comment by ydjainopensource** [comment]
It would be definitely beneficial for mainframe people. The [Marist Community Cloud ](https://linuxone20.cloud.marist.edu/cloud/#/login) runs on quite old hardware which 4.14 does not support. We need 4.4.x to run on these. And there are still quite a few machine having even older hardware. Yes, maintenance does happen to be an issue but we can have at least the versions which are still prominently used. We add support for 

- 3.10 :  RHEL 7 runs on this
- 3.12 :  SLES 12 runs this
-  4.4 :   Ubuntu 16.04 runs this.
- 4.15 :  Ubuntu 18.04 runs on these. 

Although, the kernel inside the vm shouldn't really be affected by the host kernel. But if the hardware does not support the kernel then it would just fail in mysterious ways. This is gonna be difficult for the users to figure out. Hence, we just provide the kernel version which the LTS supports and they just run with it. WDYT? @jodh-intel @Weichen81

**Comment by jodh-intel** [comment]
@ydjainopensource - That does sound like an interesting way to look at this problem: providing kernel configs for kernel versions supported by LTS distro versions.

We'd expect our kernel configs to be smaller (less options enabled) than a full LTS host kernel of course but it would make sense to "follow" the LTS releases given we use them for:

- our CI environments.
- osbuilder images for guest "mini O/S" images and initrd.

If we were to do this, I think we might need to have nominated "owners" / "maintainers" for these config files along with tooling to detect changes in the LTS distro kernel configs (admittedly unlikely for LTS kernels, but you never know I guess).

wdyt @marcov, @Pennyzct, @nitkon, @grahamwhaley, @egernst, @bergwolf, @jcvenegas ?

**Comment by jcvenegas** [comment]
@jodh-intel agree this needs maintenance and a way we ensure they keep working on each release, that could be adding jobs to the CI but I am afraid we have a very busy CI today.

**Comment by jodh-intel** [comment]
@jcvenegas - agreed. Unless we get further CI resource donations, the "silver bullet" is going to have to be [zuul](https://github.com/kata-containers/ci/issues/42).

**Comment by marcov** [comment]
It's probably going to be a a dumb comment, but I am not understanding the reasoning here. 
To recap:
1. We'd like to support a wide range of HW.
2. Old HW runs on old kernel versions.
3. We need guest VM kernel versions to be the same as (2.).


* Is (3.) required because of the specific hypervisor config being used? 
* Would it be acceptable to support old HW with less aggressive optimizations to avoid the hassle of testing and supporting many different configs?

I am writing this because having a VM should give the advantage of abstracting on the underlying HW while this is going in the opposite direction.

**Comment by jodh-intel** [comment]
Hi @marcov,

> 3. We need guest VM kernel versions to be the same as (2.).

That isn't the case - the guest kernel can (and generally will) be newer than the host kernel. We hit problems though when the guest kernel  / hypervisor require particular features from the host kernel as that will constrain the features available in the guest kernel.

Our general approach is to be tolerant of old host kernels and downgrade gracefully where possible of course. A good example of this is what happens if you enable vsock in `configuration.toml` but the host does not support it:

- https://github.com/kata-containers/runtime/blob/master/cli/config.go#L344..L352

**Comment by marcov** [comment]
thanks @jodh-intel, now I am starting to see your point.

> That isn't the case - the guest kernel can (and generally will) be newer than the host kernel. 

I see, at first I understood that we kept the same version.

> We hit problems though when the guest kernel / hypervisor require particular features from the host kernel as that will constrain the features available in the guest kernel.

So how we avoid this? We aim to have a set of minimal guest kernel configs to limit the interdependence with the host kernel as much as possible?
