### ISSUE TITLE
Fedora packaging and QEMU forks

### ISSUE THREAD

**Issue by lsm5** [kata-containers/packaging#73]
So, I've taken up packaging kata containers [for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1585446). I'm looking at qemu-lite and qemu-vanilla packages. So, IIUC, those are forks of QEMU, correct?

Have we checked to see if the default 'qemu' package could be used/extended to suit kata containers?
Just that forking sounds like trouble unless real good reason.

(I'm both a QEMU and a Kata n00b, and I'll probably have more questions as we go, so please be gentle :) )

**Comment by jodh-intel** [comment]
Hi @lsm5 - Welcome to the project! :smile:

OK, deep breath...

`qemu-lite` is "vanilla qemu + a set of patches" where those patches are designed to speed up boot and reduce memory consumption:

- https://github.com/kata-containers/qemu/commits/qemu-lite-2.11.0
- https://github.com/kata-containers/packaging/blob/master/qemu-lite/_service-template

However, the difference between `qemu-lite` and qemu upstream is now pretty small as most of the patches have been accepted upstream. For that reason, we also have a `qemu-vanilla` package which is just the upstream + a single patch to fix the `configure` script I believe:

- https://github.com/kata-containers/qemu/commits/stable-2.11
- https://github.com/kata-containers/packaging/blob/master/qemu-vanilla/_service-template

We are also looking at providing a static build (see https://github.com/kata-containers/packaging/issues/66) but I'm not sure if that would be for `qemu-vanilla` or `qemu-lite` (or both) at this stage. Can you comment @devimc, @jcvenegas, @egernst?

Since Kata works with a vanilla qemu, it should also work with the distro-packaged version of qemu, but there may be performance / memory density differences which @grahamwhaley may have information on.

/cc @Pennyzct, @nitkon.

**Comment by jodh-intel** [comment]
btw, you might want to run through our existing Fedora install guide to get a working system installed so you can have a play around with it:

- https://github.com/kata-containers/documentation/blob/master/install/fedora-installation-guide.md
  (I'd recommend choosing the [docker option](https://github.com/kata-containers/documentation/blob/master/install/docker/fedora-docker-install.md) at the end of that doc for simplicity+speed :)

**Comment by Pennyzct** [comment]
cc @Weichen81

**Comment by jodh-intel** [comment]
Hopefully it won't be too bad as we already have a spec file:

- https://github.com/kata-containers/packaging/blob/master/obs-packaging/qemu-lite/qemu-lite.spec-template (note the use of the `configure-hypervisor.sh` script in there to generate the build options).

Clear Linux also has a spec file (just to build - it doesn't actually use rpms as part of the distro):

- https://github.com/clearlinux-pkgs/kata-qemu-lite/blob/master/kata-qemu-lite.spec

/cc @jcvenegas, @egernst.

**Comment by lsm5** [comment]
@jodh-intel ah yup, sorry I was under the impression that packaging of forks was a problem to begin with, but seems I was mistaken. As long as the fork doesn't conflict in any way with the default package, we should be good to go.

I've been working on the qemu-lite spec file, and make fails complaining about some files not being found. Is this a good place to discuss those, or should I open a new issue on the kata qemu fork (The issue tracker isn't enabled there btw)

**Comment by jodh-intel** [comment]
Here is prolly the best place. Yeah, we are careful to ensure `qemu-lite` and `qemu-vanilla` are co-installable with the distro-packaged version of `qemu`.

**Comment by lsm5** [comment]
So, if I used the source tarball from https://github.com/kata-containers/qemu/archive/6ba2bfbee9a80bfd03605c5eb2ca743c8b68389e/qemu-6ba2bfb.tar.gz it would give me compilation errors (fatal error: input-keymap-linux-to-qcode.c no such file or directory). But when I used the tarball extracted from the [OSBS srpm](https://download.opensuse.org/repositories/home:/katacontainers:/release/Fedora_28/src/qemu-lite-2.11.0+git.6ba2bfbee9-43.1.src.rpm), it seemed to build just fine.

So, could you please tell me if there was anything additional done to generate the tarball that's used in the OSBS srpm? This is mainly just for my understanding to trace things back to git.

My updated spec file is [here](https://pagure.io/kata-rpm-reviews/blob/master/f/qemu-lite/qemu-lite.spec)

**Comment by jodh-intel** [comment]
Any thoughts on ^ @jcvenegas?

**Comment by lsm5** [comment]
Also, is this currently x86_64 only? [Koji build](https://koji.fedoraproject.org/koji/taskinfo?taskID=27786228) failed for all other arches.

**Comment by jodh-intel** [comment]
Yes, we're waiting for others in the community to help out with other architectures.

/cc @Pennyzct, @nitkon.

**Comment by jcvenegas** [comment]
@lsm5  sorry for the delay about missing files. 

The OBS build is cloning the qemu git repository and in the clone is downloading the sub-modules. To build qemu with options we use qemu require two submodules.

https://github.com/qemu/capstone/archive/22ead3e0bfdb87516656453336160e0a37b066bf.tar.gz
https://github.com/qemu/keycodemapdb/archive/10739aa26051a5d49d88132604539d3ed085e72e.tar.gz

To allow this in systems like koji you could add them as source 1 and 2.

Clear Linux already did something similar:
https://github.com/clearlinux-pkgs/kata-qemu-lite/blob/master/kata-qemu-lite.spec#L10

**Comment by lsm5** [comment]
@jcvenegas ack, that helps, thanks a lot!

**Comment by jcvenegas** [comment]
@lsm5 is this issue now solved, let me know if you have more questions related with this or the packaging of any other component.
